### ISSUE TITLE
Add/document getting consul from an internal url

### ISSUE THREAD

**Issue by swilson-uscis** [sous-chefs/consul#383]
Based on:
https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_installation_binary.rb#L38
it doesn't appear this is currently supported (and surely isn't documented/obvious)

**Comment by legal90** [comment]
Hi @swilson-uscis 
The answer is here: https://github.com/johnbellone/consul-cookbook/issues/342#issuecomment-249743094
You can override `node['consul']['options']['archive_url']` by any string (interpolated variables `base_name` and `variables` could be used, but not required). Example:
```ruby
node.override['consul']['options']['archive_url'] = "https://my.host.org/consul.zip"
```

But yeah, we should definitely document such things... :(

**Comment by damacus** [comment]
Closing as fixed.
