### ISSUE TITLE
stop signal should be SIGINT not SIGTERM

### ISSUE THREAD

**Issue by Wing924** [sous-chefs/consul#479]
/etc/systemd/system/consul.service
It should be:
```diff
--- /etc/systemd/system/consul.service	2017-11-17 07:22:20.041052788 +0000
+++ consul.service	2017-11-19 23:12:24.208171097 +0000
@@ -7,7 +7,7 @@
 Environment="GOMAXPROCS=2" "PATH=/usr/local/bin:/usr/bin:/bin"
 ExecStart=/opt/consul/1.0.0/consul agent -config-file=/etc/consul/consul.json -config-dir=/etc/consul/conf.d
 ExecReload=/bin/kill -HUP $MAINPID
-KillSignal=TERM
+KillSignal=INT
 User=consul
 WorkingDirectory=/var/lib/consul
```
TERM means force stop process while INT means graceful stop.

ref. https://www.consul.io/docs/agent/basics.html#stopping-an-agent

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by theanirudhvyas** [comment]
I'd like to pick up the issue, if it is still relevant. @damacus will raise a PR for it.
