### ISSUE TITLE
tls_cipher_suites should be a comma separated list

### ISSUE THREAD

**Issue by Lasering** [sous-chefs/consul#484]
The recipe should convert the `tls_cipher_suites` array to a CSV which is what the consul agent is expecting. Otherwise we get the following error:
```
* 'tls_cipher_suites' expected type 'string', got unconvertible type '[]interface {}'
```

**Comment by mfischer90** [comment]
This still seems to be an issue, makes using this variable impossible

**Comment by ragarcia26** [comment]
bump, seeing this too

**Comment by mfischer90** [comment]
#501 created to fix

**Comment by damacus** [comment]
Closing via #501
