### ISSUE TITLE
windows_path in library breaks with linux chef-client < 13.x.x and windows community cookbook >= 5.0.0

### ISSUE THREAD

**Issue by knightorc** [sous-chefs/consul#503]
We unlocked our copy of consul-cookbook from windows ~> 3.1 awhile ago, since it block us using Windows ~> 4.0

In testing the new Windows 5.0.0 cookbook I discovered the use of the windows_path here:

https://github.com/johnbellone/consul-cookbook/blob/5fd61fbcd97992e394531fbde41e67fcf6c24268/libraries/consul_installation_binary.rb#L67

breaks linux use of this cookbook when the linux client version is still 12.x.x,  in our case, we're 12.22.3 on client on linux, but 13.10.0 on windows.

This is just a heads up to anyone else in a hybrid environment that has also unlocked the depends in their copy of the cookbook.

The moment this cookbook requires chef-client >= 13.0+ this issue will go away.

From: Windows cookbook CHANGELOG

`as of chef-client 13.0+ and 13.4+ windows_task and windows_path are now included in the Chef client`

**Comment by knightorc** [comment]
The big change in the Windows community cookbook @5.0.0 is the removal of the cookbook resource `windows_path`

**Comment by gdavison** [comment]
Does the windows cookbook 4.x work for you? I've had to lock a few cookbooks to ~> 4.3 at work. Want to create a PR? :)

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs
