### ISSUE TITLE
Release on chef supermarket

### ISSUE THREAD

**Issue by Lasering** [sous-chefs/consul#505]
This repo/cookbook has a lot of merged changes that would be very helpful if released on Chef supermarket.

I can help releasing it to supermarket.

**Comment by damacus** [comment]
@Lasering if you can drop by the sous-chefs room on the Chef community Slack an introduce yourself, we'll happily have another maintainer onboard! 

Thanks,
Dan

**Comment by Lasering** [comment]
Hi @damacus, I'm still available to help release the cookbook to the supermarket.
