### ISSUE TITLE
Support for the new parameter  enable-local-script-checks

### ISSUE THREAD

**Issue by tohimon** [sous-chefs/consul#517]
Hi
could you please add support for the new parameter  enable-local-script-checks introduced in consul 1.3.0 and backported to versions 1.2.4, 1.1.1, 1.0.8, and 0.9.4 ?
Thanks

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by emachnic** [comment]
@tohimon It looks like #542 may have resolved this. Can you check?

**Comment by tohimon** [comment]
It has, thank you!
