### ISSUE TITLE
Support Consul 1.4.0+ ACL system

### ISSUE THREAD

**Issue by scalp42** [sous-chefs/consul#520]
Placeholder issue, as we need Diplomat to be updated before but a simple resource matching the name of a token on the new ACL system will fail.

For example, this resource will fail on Consul 1.4.x:

```ruby
consul_acl 'anonymous' do
   xxxxx
end
```

Related to https://github.com/WeAreFarmGeek/diplomat/issues/193

**Comment by scalp42** [comment]
Working on it.

**Comment by tas50** [comment]
Closing this out since this was merged in
