### ISSUE TITLE
Poise dependency is abandoned

### ISSUE THREAD

**Issue by SuperQ** [sous-chefs/consul#551]
## Brief Description

The cookbook depends on [poise](https://github.com/poise/poise), which is now archived and abandoned. This should be removed to avoid future cookbook breakage.

## Cookbook version

3.0.0

## Chef-Infra Version

Any

## Platform details

Any

**Comment by JohnRoesler** [comment]
Yes - we should remove the poise dependency. It's been on our list - just haven't gotten to it. Fancy taking a run at it?

**Comment by SuperQ** [comment]
Part of the poise setup is picking a supervisor. What is the recommended replacement? Normally we build our cookbooks services with `systemd_unit` resources.

**Comment by JohnRoesler** [comment]
A lot of our cookbooks are moving to supporting systemd only as the major OS versions seem to be moving that way. 

This cookbook also should be moved to custom resources as that's the best practice pattern today...lots of work needed here.
