### ISSUE TITLE
Rewrite Consul cookbook to use custom resources

### ISSUE THREAD

**Issue by emachnic** [sous-chefs/consul#555]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

This cookbook is a mess of custom libraries that are difficult to maintain.

## :grey_question: Possible Solution

We should rewrite the Consul cookbook to use [Chef custom resources](https://docs.chef.io/custom_resources/)

## :heavy_plus_sign: Additional context

#551 
#515

**Comment by johnbellone** [comment]
I totally agree here, but unfortunately do not have time to do it myself.

**Comment by johnbellone** [comment]
I think its fair to assume major version breaking changes. 🏛️🚚

**Comment by emachnic** [comment]
@johnbellone I've actually been working on a rewrite for this for a major version release that will leverage custom resources. It's been a long process thus far and I've had to refocus but hopefully be able to pick it back up

**Comment by theanirudhvyas** [comment]
Instead of doing a complete rewrite in a single commit, I'll suggest that we gradually migrate individual features (like consulDefinition) one at a time in separate releases. This will help us ensure backward compatibility and also reduce the probability of bugs.
WDYT @johnbellone @emachnic ?

**Comment by emachnic** [comment]
@theanirudhvyas that would normally be the best way but, after having gone through a lot of this cookbook, a complete rewrite is probably the most expeditious.
